language: python
python:
        - "3.6"
install:
        - pip3 install python-coveralls
        - pip3 install coverage
script:
        - coverage run test_rpn.py
        - coverage report -m
after_success:
        - coveralls
